### PR TITLE
Make compatible with kitspace.org

### PR DESCRIPTION
**Pull request by kasbah**
Hey, 

I had a go at sorting out the BOM. Is `pcb_design` the right folder to be looking at? I don't have Protel so I just went by the PNG and the gerber files. It seems to say the capacitor is 1000uF 12V and the diameter is 6mm, that seems really hard to find. 12mm or a tantalum would be much easier.

### CODE REVIEW

**Comment by rwb27** [comment]
Hi @kasbah, thanks for getting involved - I think when Valerian updated the PCB design he added a folder rather than updating the v1 files... sorry if that's a pain!  I will try to tidy that up soon.  In the meantime, the up to date files are in sangaboard_v2.  It is a fairly similar design, but with a few extra headers broken out and a couple of components added.  The BOM shouldn't have changed too much, I think.

**Comment by rwb27** [comment]
Thanks - this looks useful!  I've just popped it in to kitspace.org, it's taking its time!  I wonder if maybe kitspace.yaml needs to go at the top level?  Perhaps I should just be patient.  Once I've tidied this up, it would be super to be able to order the components via kitspace.

**Comment by kasbah** [comment]
Nice. Sorry yes, I am an idiot and just introduced a bug into the preview/submit thing. Please try again in 10 mins and do a cache-free refresh of the site (Ctrl-Shift-R) if it still gives you problems then.

**Comment by rwb27** [comment]
cool, I can see the board now (though I can't see the holes or read the text) and the BOM you added - I've got a README.rst rather than .md (for compatibility with Python auto-documentation stuff) so I'll need to figure out if I can do both.  I'll add an issue so I remember to figure that one out.

**Pull request merged**
