### PR TITLE
Switch kitspace input to sangaboard

### PR DESCRIPTION
**Pull request by kasbah**
Hey, this switches things over to the newer board and sorts out/avoids remaining issues. I'll push a fix to Kitspace to at least display the .rst in a raw format on the page for now.

### CODE REVIEW

**Comment by kasbah** [comment]
I added some partial reStructured text support. Your readme is actually in markdown but with an .rst extension and by coincidence that all works out with the way I have done things (trying to convert rst to markdown and then to html).

**Comment by kasbah** [comment]
ping @rwb27

**Comment by rwb27** [comment]
Sorry for leaving this so long - I'll pull it now.  I should probably rearrange the repo so that there is only one folder of PCB designs though!

**Comment by kasbah** [comment]
No problem. Yes, just remember to update the `kitspace.yaml` to point it at the right folder when you do. 

There is unfortunately a problem with how the drill file is rendered which I want to solve before putting it up. https://github.com/tracespace/tracespace/issues/73

**Pull request merged**
