### PR TITLE
Bugfix for query code if unexpected items appear in buffer between write and read

### PR DESCRIPTION
**Pull request by julianstirling**
Also:
* Updated .gitignore for some linux stuff
* Deleted stray .pyc file
* Moved StepperF_alt files so automatically found by Arduino IDE
* Updated arduino readme with a little info

### CODE REVIEW

**Comment by rwb27** [comment]
Just to check I'm not misunderstanding - is there a reason you put light sensor support into OpenFlexureStage, rather than into OpenFlexureStageWithLightSensor?  There should already be support for the features you added there...

**Comment by julianstirling** [comment]
Oh FFS. Due to tunnel vision once I got it compiling. I searched for the features in the IDE, didn't go back to the folder and realise there was another python file. I might move the OpenFlexureStageWithLightSensor into stage.py as it seems sensible that they are together.

**Comment by rwb27** [comment]
perhaps - I don't think it really matters how they're arranged, and some folk were confused by the presence of the light sensor code hence my separating it out...  A nice to-do would be to make sure the class checks that the firmware features match (e.g. that if you use the one without light sensor support, that you have a Stage not a StageWithLightSensor) but that can wait.

**Comment by julianstirling** [comment]
I just think that if I was looking for a class which ran my stage which also had a light sensor I would look in a module called stage, not called light sensor. I know because I wasted a whole evening doing that.

In the combined class I did some checking for whether the light sensor is in the firmware, I can separate that into OpenFlexureStageWithLightSensor easily. There is also some extra error handling in my implementation, but it is less pretty with "properties" so I will try and create a best of both worlds and merge some of the handling in.

**Comment by julianstirling** [comment]
Further thoughts while walking to work:
This is a core library for the stage controller, the stage controller is used in the microscope and the fibre stage and probably will be repurposed again. Also other features such as limit switches/lighting controls may be added over time. Therefore, to future proof the code it does make more sense to have one class called stage, and the board on communication to list its attached modules. Depending on the attached modules the class opens support for these.

This way let say we make a version of the microscope that has a light sensor (strange example, but maybe we want to monitor the light level) then simply the software can check whether OpenFlexureStage.light_sensor is available when the connection is established and enable/disable those commands. This way if we then add a light controller we can check if OpenFlexureStage.light_controller is available to, this is much cleaner than having classes:

1. OpenFlexureStage
1. OpenFlexureStageWithLightSensor
1. OpenFlexureStageWithLightController
1. OpenFlexureStageWithLightSensorAndLightController

As we eventually add more modules this will get very unwieldy very quickly.

I know you might argue this is not priority #1,  but as I am just starting on getting up to speed with the fibre stage, and debugging why I couldn't connect I have become immersed in the library to locate the issues I had. It seems sensible to tidy the library now while it is fresh in my brain and then rebuild the fibre stage code around it, otherwise the cost of the upgrade will grow and it wont happen until it is a much bigger job.

**Comment by rwb27** [comment]
That does sound like a pretty reasonable way of doing it - though I will argue that it's not a super high priority thing to do, so it only makes sense if it's a relatively quick fix...

My suggestion was going to be using "mixin" classes (the advantage of that is you could construct a subclass that includes whichever functionality you want) but that gets unwieldy when writing code that supports but doesn't require a particular feature.  Also, using multiple inheritance goes wrong a lot...

**Comment by julianstirling** [comment]
Well it is done now. Considering it took me a day to understand why I was getting weird Arduino compiler errors, and weird serial query errors, half a day restructuring code is, I think, time well spent. Especially as I now understand exactly what is happening in the library so, when I start using it and inevitably hit bugs I will actually be able to fix them in a reasonable amount of time.

**Comment by rwb27** [comment]
Just had another look through this, and I can't see that it will break anything or slow it down.  I'll pull it and then start folding in the python 3 stuff from Cambridge - we might even manage another release on pypi soon!

**Pull request merged**
